# Generated by Django 4.2.30 on 2026-06-08 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_conversation_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
