# Generated by Django 4.2.30 on 2026-06-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_favorite_favorite_unique_user_favorite_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
